import { Geist, Poppins } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@mui/material";
import theme from "../components/theme/theme";
import Navigation from "../components/global/navigation";
import Footer2 from "../components/global/footer2";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const poppins = Poppins({
    variable: "--font-poppins",
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
    subsets: ["latin"],
});

export const metadata = {
    title: "JBS Technology",
    description: "Generated by create next app",
    icons: {
        icon: "/favicon.svg",
    },
};


export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body className={`${poppins.variable} ${geistSans.variable}`}>
        <ThemeProvider theme={theme}>
            <Navigation />
            {children}
            <Footer2 />
        </ThemeProvider>
        </body>
        </html>
    );
}
